swagger: "2.0"
info:
    title: Enduro API
    version: ""
host: localhost:9000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /batch:
        get:
            tags:
                - batch
            summary: status batch
            description: Retrieve status of current batch operation.
            operationId: batch#status
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BatchStatusResponseBody'
                        required:
                            - running
            schemes:
                - http
        post:
            tags:
                - batch
            summary: submit batch
            description: Submit a new batch
            operationId: batch#submit
            parameters:
                - name: SubmitRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BatchSubmitRequestBody'
                    required:
                        - path
            responses:
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/BatchSubmitResponseBody'
                        required:
                            - workflow_id
                            - run_id
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BatchSubmitNotValidResponseBody'
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/BatchSubmitNotAvailableResponseBody'
            schemes:
                - http
    /batch/hints:
        get:
            tags:
                - batch
            summary: hints batch
            description: Retrieve form hints
            operationId: batch#hints
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BatchHintsResponseBody'
            schemes:
                - http
    /package:
        get:
            tags:
                - package
            summary: list package
            description: List all stored packages
            operationId: package#list
            parameters:
                - name: name
                  in: query
                  required: false
                  type: string
                - name: aip_id
                  in: query
                  required: false
                  type: string
                  format: uuid
                - name: earliest_created_time
                  in: query
                  required: false
                  type: string
                  format: date-time
                - name: latest_created_time
                  in: query
                  required: false
                  type: string
                  format: date-time
                - name: status
                  in: query
                  required: false
                  type: string
                  enum:
                    - new
                    - in progress
                    - done
                    - error
                    - unknown
                    - queued
                    - pending
                    - abandoned
                - name: cursor
                  in: query
                  description: Pagination cursor
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PackageListResponseBody'
                        required:
                            - items
            schemes:
                - http
    /package/{id}:
        get:
            tags:
                - package
            summary: show package
            description: Show package by ID
            operationId: package#show
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to show
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PackageShowResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PackageShowNotFoundResponseBody'
                        required:
                            - message
                            - id
            schemes:
                - http
        delete:
            tags:
                - package
            summary: delete package
            description: Delete package by ID
            operationId: package#delete
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to delete
                  required: true
                  type: integer
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PackageDeleteNotFoundResponseBody'
                        required:
                            - message
                            - id
            schemes:
                - http
    /package/{id}/cancel:
        post:
            tags:
                - package
            summary: cancel package
            description: Cancel package processing by ID
            operationId: package#cancel
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to remove
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/PackageCancelNotRunningResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PackageCancelNotFoundResponseBody'
                        required:
                            - message
                            - id
            schemes:
                - http
    /package/{id}/download:
        get:
            tags:
                - package
            summary: download package
            description: Download package by ID
            operationId: package#download
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to look up
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PackageDownloadNotFoundResponseBody'
                        required:
                            - message
                            - id
            schemes:
                - http
    /package/{id}/preservation-actions:
        get:
            tags:
                - package
            summary: preservation-actions package
            description: List all preservation actions by ID
            operationId: package#preservation-actions
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to look up
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PackagePreservationActionsResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PackagePreservationActionsNotFoundResponseBody'
                        required:
                            - message
                            - id
            schemes:
                - http
    /package/{id}/retry:
        post:
            tags:
                - package
            summary: retry package
            description: Retry package processing by ID
            operationId: package#retry
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to retry
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/PackageRetryNotRunningResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PackageRetryNotFoundResponseBody'
                        required:
                            - message
                            - id
            schemes:
                - http
    /package/{id}/workflow:
        get:
            tags:
                - package
            summary: workflow package
            description: Retrieve workflow status by ID
            operationId: package#workflow
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to look up
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PackageWorkflowResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PackageWorkflowNotFoundResponseBody'
                        required:
                            - message
                            - id
            schemes:
                - http
    /package/bulk:
        get:
            tags:
                - package
            summary: bulk_status package
            description: Retrieve status of current bulk operation.
            operationId: package#bulk_status
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PackageBulkStatusResponseBody'
                        required:
                            - running
            schemes:
                - http
        post:
            tags:
                - package
            summary: bulk package
            description: Bulk operations (retry, cancel...).
            operationId: package#bulk
            parameters:
                - name: BulkRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/PackageBulkRequestBody'
                    required:
                        - operation
                        - status
            responses:
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/PackageBulkResponseBody'
                        required:
                            - workflow_id
                            - run_id
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/PackageBulkNotValidResponseBody'
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/PackageBulkNotAvailableResponseBody'
            schemes:
                - http
    /package/monitor:
        get:
            tags:
                - package
            summary: monitor package
            operationId: package#monitor
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/PackageMonitorResponseBody'
            schemes:
                - ws
    /swagger/swagger.json:
        get:
            tags:
                - swagger
            summary: Download internal/api/gen/http/openapi.json
            description: JSON document containing the API swagger definition.
            operationId: swagger#/swagger/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BatchHintsResponseBody:
        title: BatchHintsResponseBody
        type: object
        properties:
            completed_dirs:
                type: array
                items:
                    type: string
                    example: Debitis et sit minima repudiandae dicta saepe.
                description: A list of known values of completedDir used by existing watchers.
                example:
                    - Iure quae modi.
                    - Natus quaerat dicta sit voluptatibus error.
        example:
            completed_dirs:
                - Excepturi rem deserunt.
                - Nobis aut.
    BatchStatusResponseBody:
        title: BatchStatusResponseBody
        type: object
        properties:
            run_id:
                type: string
                example: Dolorem nesciunt recusandae qui optio sed consectetur.
            running:
                type: boolean
                example: false
            status:
                type: string
                example: Id aut modi maiores sit.
            workflow_id:
                type: string
                example: Aliquam dolor dolorum.
        example:
            run_id: Corrupti sunt ad deleniti sunt nostrum.
            running: false
            status: Amet ipsa dicta aperiam necessitatibus ipsam.
            workflow_id: Molestias quae.
        required:
            - running
    BatchSubmitNotAvailableResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: submit_not_available_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BatchSubmitNotValidResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: submit_not_valid_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BatchSubmitRequestBody:
        title: BatchSubmitRequestBody
        type: object
        properties:
            completed_dir:
                type: string
                example: Fugiat et non.
            path:
                type: string
                example: Fuga aut.
            retention_period:
                type: string
                example: Et velit suscipit.
        example:
            completed_dir: Totam atque.
            path: Recusandae quasi voluptatem iusto consequatur qui aut.
            retention_period: Quibusdam vitae ut.
        required:
            - path
    BatchSubmitResponseBody:
        title: BatchSubmitResponseBody
        type: object
        properties:
            run_id:
                type: string
                example: Quibusdam dolor aut sit in.
            workflow_id:
                type: string
                example: Illum neque veritatis ut libero maxime alias.
        example:
            run_id: Et dignissimos explicabo soluta et autem id.
            workflow_id: Commodi possimus et.
        required:
            - workflow_id
            - run_id
    EnduroPackagePreservationActionsActionResponseBody:
        title: 'Mediatype identifier: application/vnd.enduro.package-preservation-actions-action; view=default'
        type: object
        properties:
            action_id:
                type: string
                example: Blanditiis quasi quam architecto.
            id:
                type: integer
                example: 6920606468320741910
                format: int64
            name:
                type: string
                example: In non possimus quia expedita quia.
            started_at:
                type: string
                example: "2011-07-20T04:03:51Z"
                format: date-time
            status:
                type: string
                example: failed
                enum:
                    - unspecified
                    - complete
                    - processing
                    - failed
        description: PreservationAction describes a preservation action. (default view)
        example:
            action_id: Totam reiciendis reiciendis.
            id: 16123501299694023279
            name: Sunt quia explicabo est vitae aperiam.
            started_at: "1991-12-05T12:01:10Z"
            status: unspecified
        required:
            - id
            - action_id
            - name
            - status
            - started_at
    EnduroPackagePreservationActionsActionResponseBodyCollection:
        title: 'Mediatype identifier: application/vnd.enduro.package-preservation-actions-action; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/EnduroPackagePreservationActionsActionResponseBody'
        description: EnduroPackage-Preservation-Actions-ActionCollectionResponseBody is the result type for an array of EnduroPackage-Preservation-Actions-ActionResponseBody (default view)
        example:
            - action_id: Eum maiores totam in numquam itaque nulla.
              id: 7057450215175192646
              name: Sint maiores odit in quia tempora.
              started_at: "1998-10-31T09:15:13Z"
              status: unspecified
            - action_id: Eum maiores totam in numquam itaque nulla.
              id: 7057450215175192646
              name: Sint maiores odit in quia tempora.
              started_at: "1998-10-31T09:15:13Z"
              status: unspecified
            - action_id: Eum maiores totam in numquam itaque nulla.
              id: 7057450215175192646
              name: Sint maiores odit in quia tempora.
              started_at: "1998-10-31T09:15:13Z"
              status: unspecified
            - action_id: Eum maiores totam in numquam itaque nulla.
              id: 7057450215175192646
              name: Sint maiores odit in quia tempora.
              started_at: "1998-10-31T09:15:13Z"
              status: unspecified
    EnduroPackageWorkflowHistoryResponseBody:
        title: 'Mediatype identifier: application/vnd.enduro.package-workflow-history; view=default'
        type: object
        properties:
            details:
                type: string
                description: Contents of the event
                example: Sapiente totam ipsa minus.
                format: binary
            id:
                type: integer
                description: Identifier of package
                example: 6418809734831999911
                format: int64
            type:
                type: string
                description: Type of the event
                example: Non perspiciatis.
        description: WorkflowHistoryEvent describes a history event in Temporal. (default view)
        example:
            details: Quas beatae ex voluptatum cum.
            id: 15522650713237053992
            type: Dolor voluptatem eum.
    EnduroPackageWorkflowHistoryResponseBodyCollection:
        title: 'Mediatype identifier: application/vnd.enduro.package-workflow-history; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/EnduroPackageWorkflowHistoryResponseBody'
        description: EnduroPackage-Workflow-HistoryCollectionResponseBody is the result type for an array of EnduroPackage-Workflow-HistoryResponseBody (default view)
        example:
            - details: Sapiente dolorem id dolor rerum sunt sint.
              id: 14390278263520728367
              type: Minima tempora repudiandae molestias ratione fugiat.
            - details: Sapiente dolorem id dolor rerum sunt sint.
              id: 14390278263520728367
              type: Minima tempora repudiandae molestias ratione fugiat.
    EnduroStoredPackageResponseBody:
        title: 'Mediatype identifier: application/vnd.enduro.stored-package; view=default'
        type: object
        properties:
            aip_id:
                type: string
                description: Identifier of Archivematica AIP
                example: E058AD50-5D7F-E9A8-E010-D33044724992
                format: uuid
            completed_at:
                type: string
                description: Completion datetime
                example: "1972-09-15T19:31:34Z"
                format: date-time
            created_at:
                type: string
                description: Creation datetime
                example: "2006-05-08T03:21:07Z"
                format: date-time
            id:
                type: integer
                description: Identifier of package
                example: 3488603430297288186
                format: int64
            name:
                type: string
                description: Name of the package
                example: Similique qui.
            run_id:
                type: string
                description: Identifier of latest processing workflow run
                example: F25C441B-B3AA-5871-1077-53EACA084D5A
                format: uuid
            started_at:
                type: string
                description: Start datetime
                example: "2010-10-16T23:35:57Z"
                format: date-time
            status:
                type: string
                description: Status of the package
                default: new
                example: done
                enum:
                    - new
                    - in progress
                    - done
                    - error
                    - unknown
                    - queued
                    - pending
                    - abandoned
            workflow_id:
                type: string
                description: Identifier of processing workflow
                example: CEF3CAF7-AB82-083A-2F08-9497BE6B7488
                format: uuid
        description: StoredPackage describes a package retrieved by the service. (default view)
        example:
            aip_id: AC2E8D12-84E7-ADAA-5045-93C4FF40145F
            completed_at: "1970-04-04T05:07:06Z"
            created_at: "1975-12-19T17:23:14Z"
            id: 2454704535101245703
            name: Sint et quae quisquam.
            run_id: 76150F6F-C16D-33A6-B049-F5AE2D7C6385
            started_at: "1981-05-29T01:47:50Z"
            status: abandoned
            workflow_id: 43632E4F-A034-6412-7CEA-7CD0E1AED81D
        required:
            - id
            - status
            - created_at
    EnduroStoredPackageResponseBodyCollection:
        title: 'Mediatype identifier: application/vnd.enduro.stored-package; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/EnduroStoredPackageResponseBody'
        description: EnduroStored-PackageCollectionResponseBody is the result type for an array of EnduroStored-PackageResponseBody (default view)
        example:
            - aip_id: A45D83CF-F038-77BB-220E-D79EFC31D198
              completed_at: "1990-08-20T23:48:32Z"
              created_at: "1974-07-21T19:27:25Z"
              id: 5956403125240755452
              name: Labore commodi voluptatem tenetur nesciunt reiciendis tempore.
              run_id: 76FB876C-96AC-91E7-BD21-B0C2988DDF65
              started_at: "1979-06-07T07:41:30Z"
              status: new
              workflow_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
            - aip_id: A45D83CF-F038-77BB-220E-D79EFC31D198
              completed_at: "1990-08-20T23:48:32Z"
              created_at: "1974-07-21T19:27:25Z"
              id: 5956403125240755452
              name: Labore commodi voluptatem tenetur nesciunt reiciendis tempore.
              run_id: 76FB876C-96AC-91E7-BD21-B0C2988DDF65
              started_at: "1979-06-07T07:41:30Z"
              status: new
              workflow_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
            - aip_id: A45D83CF-F038-77BB-220E-D79EFC31D198
              completed_at: "1990-08-20T23:48:32Z"
              created_at: "1974-07-21T19:27:25Z"
              id: 5956403125240755452
              name: Labore commodi voluptatem tenetur nesciunt reiciendis tempore.
              run_id: 76FB876C-96AC-91E7-BD21-B0C2988DDF65
              started_at: "1979-06-07T07:41:30Z"
              status: new
              workflow_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
            - aip_id: A45D83CF-F038-77BB-220E-D79EFC31D198
              completed_at: "1990-08-20T23:48:32Z"
              created_at: "1974-07-21T19:27:25Z"
              id: 5956403125240755452
              name: Labore commodi voluptatem tenetur nesciunt reiciendis tempore.
              run_id: 76FB876C-96AC-91E7-BD21-B0C2988DDF65
              started_at: "1979-06-07T07:41:30Z"
              status: new
              workflow_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
    PackageBulkNotAvailableResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: bulk_not_available_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PackageBulkNotValidResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: bulk_not_valid_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PackageBulkRequestBody:
        title: PackageBulkRequestBody
        type: object
        properties:
            operation:
                type: string
                example: abandon
                enum:
                    - retry
                    - cancel
                    - abandon
            size:
                type: integer
                default: 100
                example: 14167350259653879373
                format: int64
            status:
                type: string
                example: new
                enum:
                    - new
                    - in progress
                    - done
                    - error
                    - unknown
                    - queued
                    - pending
                    - abandoned
        example:
            operation: retry
            size: 7494278713778797527
            status: abandoned
        required:
            - operation
            - status
    PackageBulkResponseBody:
        title: PackageBulkResponseBody
        type: object
        properties:
            run_id:
                type: string
                example: Neque sit quia nemo sunt.
            workflow_id:
                type: string
                example: Beatae quis quis quia voluptas ut.
        example:
            run_id: Omnis laboriosam nam est ad nostrum neque.
            workflow_id: Recusandae magni quaerat cum ut qui.
        required:
            - workflow_id
            - run_id
    PackageBulkStatusResponseBody:
        title: PackageBulkStatusResponseBody
        type: object
        properties:
            closed_at:
                type: string
                example: "1986-12-10T13:38:18Z"
                format: date-time
            run_id:
                type: string
                example: Omnis aliquam qui explicabo laborum sint animi.
            running:
                type: boolean
                example: true
            started_at:
                type: string
                example: "1970-10-21T17:07:49Z"
                format: date-time
            status:
                type: string
                example: Ut iusto voluptatum explicabo voluptatum.
            workflow_id:
                type: string
                example: Quia aliquid.
        example:
            closed_at: "2012-03-22T01:52:33Z"
            run_id: Qui voluptatem.
            running: true
            started_at: "2004-04-28T16:28:39Z"
            status: Eos magni praesentium atque.
            workflow_id: Qui magni occaecati dolorem esse deleniti.
        required:
            - running
    PackageCancelNotFoundResponseBody:
        title: PackageCancelNotFoundResponseBody
        type: object
        properties:
            id:
                type: integer
                description: Identifier of missing package
                example: 10742020284310708011
                format: int64
            message:
                type: string
                description: Message of error
                example: Ut quisquam officia dolorem delectus.
        description: Package not found
        example:
            id: 12880090019776346249
            message: Et tempora similique.
        required:
            - message
            - id
    PackageCancelNotRunningResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: cancel_not_running_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PackageDeleteNotFoundResponseBody:
        title: PackageDeleteNotFoundResponseBody
        type: object
        properties:
            id:
                type: integer
                description: Identifier of missing package
                example: 8596451622752141620
                format: int64
            message:
                type: string
                description: Message of error
                example: Sint consequuntur dicta.
        description: Package not found
        example:
            id: 11128191567695799429
            message: Praesentium a itaque eligendi quo eos.
        required:
            - message
            - id
    PackageDownloadNotFoundResponseBody:
        title: PackageDownloadNotFoundResponseBody
        type: object
        properties:
            id:
                type: integer
                description: Identifier of missing package
                example: 2551462927691999941
                format: int64
            message:
                type: string
                description: Message of error
                example: Ex perspiciatis ut nam non ipsa.
        description: Package not found
        example:
            id: 6813908055992809381
            message: Cum laboriosam aliquid dolorem mollitia facilis non.
        required:
            - message
            - id
    PackageListResponseBody:
        title: PackageListResponseBody
        type: object
        properties:
            items:
                $ref: '#/definitions/EnduroStoredPackageResponseBodyCollection'
            next_cursor:
                type: string
                example: Provident molestiae sint et.
        example:
            items:
                - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  completed_at: "1981-07-18T09:32:04Z"
                  created_at: "1983-12-07T23:41:35Z"
                  id: 2608592925037585396
                  name: Vitae illum magni placeat quo.
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1998-03-18T12:36:31Z"
                  status: error
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  completed_at: "1981-07-18T09:32:04Z"
                  created_at: "1983-12-07T23:41:35Z"
                  id: 2608592925037585396
                  name: Vitae illum magni placeat quo.
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1998-03-18T12:36:31Z"
                  status: error
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
            next_cursor: Veniam magni.
        required:
            - items
    PackageMonitorResponseBody:
        title: 'Mediatype identifier: application/vnd.enduro.monitor-update; view=default'
        type: object
        properties:
            id:
                type: integer
                description: Identifier of package
                example: 9916043004669830935
                format: int64
            item:
                $ref: '#/definitions/EnduroStoredPackageResponseBody'
            type:
                type: string
                description: Type of the event
                example: Voluptatem rerum pariatur dicta.
        description: MonitorResponseBody result type (default view)
        example:
            id: 10362683600268187570
            item:
                aip_id: A45D83CF-F038-77BB-220E-D79EFC31D198
                completed_at: "1990-08-20T23:48:32Z"
                created_at: "1974-07-21T19:27:25Z"
                id: 5956403125240755452
                name: Labore commodi voluptatem tenetur nesciunt reiciendis tempore.
                run_id: 76FB876C-96AC-91E7-BD21-B0C2988DDF65
                started_at: "1979-06-07T07:41:30Z"
                status: new
                workflow_id: 7D80331A-7620-D09D-7CCB-2EF87B797732
            type: Ab eius est necessitatibus natus nostrum unde.
        required:
            - id
            - type
    PackagePreservationActionsNotFoundResponseBody:
        title: PackagePreservationActionsNotFoundResponseBody
        type: object
        properties:
            id:
                type: integer
                description: Identifier of missing package
                example: 14658862406802586238
                format: int64
            message:
                type: string
                description: Message of error
                example: Eos odit nobis est perferendis aperiam.
        description: Package not found
        example:
            id: 1582683469153866133
            message: Eius dolore beatae omnis.
        required:
            - message
            - id
    PackagePreservationActionsResponseBody:
        title: 'Mediatype identifier: application/vnd.enduro.package-preservation-actions; view=default'
        type: object
        properties:
            actions:
                $ref: '#/definitions/EnduroPackagePreservationActionsActionResponseBodyCollection'
        description: Preservation-ActionsResponseBody result type (default view)
        example:
            actions:
                - action_id: Eum maiores totam in numquam itaque nulla.
                  id: 7057450215175192646
                  name: Sint maiores odit in quia tempora.
                  started_at: "1998-10-31T09:15:13Z"
                  status: unspecified
                - action_id: Eum maiores totam in numquam itaque nulla.
                  id: 7057450215175192646
                  name: Sint maiores odit in quia tempora.
                  started_at: "1998-10-31T09:15:13Z"
                  status: unspecified
    PackageRetryNotFoundResponseBody:
        title: PackageRetryNotFoundResponseBody
        type: object
        properties:
            id:
                type: integer
                description: Identifier of missing package
                example: 6863600688512825923
                format: int64
            message:
                type: string
                description: Message of error
                example: Sit perferendis dolor dolore voluptatem omnis.
        description: Package not found
        example:
            id: 5055500684694062847
            message: Tempore asperiores facere.
        required:
            - message
            - id
    PackageRetryNotRunningResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: retry_not_running_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PackageShowNotFoundResponseBody:
        title: PackageShowNotFoundResponseBody
        type: object
        properties:
            id:
                type: integer
                description: Identifier of missing package
                example: 13136096573646845251
                format: int64
            message:
                type: string
                description: Message of error
                example: Recusandae laudantium.
        description: Package not found
        example:
            id: 13664665285220164853
            message: Quae rerum unde nobis.
        required:
            - message
            - id
    PackageShowResponseBody:
        title: 'Mediatype identifier: application/vnd.enduro.stored-package; view=default'
        type: object
        properties:
            aip_id:
                type: string
                description: Identifier of Archivematica AIP
                example: 8B791A71-1C43-AB9B-4366-12192353E1A2
                format: uuid
            completed_at:
                type: string
                description: Completion datetime
                example: "1991-10-04T15:37:19Z"
                format: date-time
            created_at:
                type: string
                description: Creation datetime
                example: "1987-06-11T05:42:28Z"
                format: date-time
            id:
                type: integer
                description: Identifier of package
                example: 9704859011707544862
                format: int64
            name:
                type: string
                description: Name of the package
                example: Magni eveniet quia voluptas fuga molestias.
            run_id:
                type: string
                description: Identifier of latest processing workflow run
                example: 6E989AEF-9C11-4862-D8B1-5CFC4F6414E0
                format: uuid
            started_at:
                type: string
                description: Start datetime
                example: "2007-09-25T19:26:55Z"
                format: date-time
            status:
                type: string
                description: Status of the package
                default: new
                example: unknown
                enum:
                    - new
                    - in progress
                    - done
                    - error
                    - unknown
                    - queued
                    - pending
                    - abandoned
            workflow_id:
                type: string
                description: Identifier of processing workflow
                example: 6BD40BD6-7AF6-FB4E-C1C1-23700A0E68DE
                format: uuid
        description: ShowResponseBody result type (default view)
        example:
            aip_id: C14F18CD-9DAC-4197-F250-EC3FBAFE81DD
            completed_at: "1978-05-06T07:43:21Z"
            created_at: "1993-12-28T06:43:35Z"
            id: 239202555132084968
            name: Est deserunt.
            run_id: 36111869-D7E7-159A-3E5F-AC3C2E0C42DD
            started_at: "1971-11-14T12:04:18Z"
            status: queued
            workflow_id: EBC096AD-D9EC-2F9C-CCD5-2819684939D3
        required:
            - id
            - status
            - created_at
    PackageWorkflowNotFoundResponseBody:
        title: PackageWorkflowNotFoundResponseBody
        type: object
        properties:
            id:
                type: integer
                description: Identifier of missing package
                example: 11053071550819203011
                format: int64
            message:
                type: string
                description: Message of error
                example: Unde nulla veritatis consequatur.
        description: Package not found
        example:
            id: 9456871970891484049
            message: Nisi quo et.
        required:
            - message
            - id
    PackageWorkflowResponseBody:
        title: 'Mediatype identifier: application/vnd.enduro.package-workflow-status; view=default'
        type: object
        properties:
            history:
                $ref: '#/definitions/EnduroPackageWorkflowHistoryResponseBodyCollection'
            status:
                type: string
                example: Incidunt fugit facilis voluptas.
        description: WorkflowResponseBody result type (default view)
        example:
            history:
                - details: Sapiente dolorem id dolor rerum sunt sint.
                  id: 14390278263520728367
                  type: Minima tempora repudiandae molestias ratione fugiat.
                - details: Sapiente dolorem id dolor rerum sunt sint.
                  id: 14390278263520728367
                  type: Minima tempora repudiandae molestias ratione fugiat.
                - details: Sapiente dolorem id dolor rerum sunt sint.
                  id: 14390278263520728367
                  type: Minima tempora repudiandae molestias ratione fugiat.
            status: Numquam enim est dolore dolorum rem.
