openapi: 3.0.3
info:
    title: Enduro API
    version: "1.0"
servers:
    - url: http://localhost:9000
paths:
    /batch:
        get:
            tags:
                - batch
            summary: status batch
            description: Retrieve status of current batch operation.
            operationId: batch#status
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BatchStatusResult'
                            example:
                                run_id: Aperiam blanditiis adipisci sint maiores repellendus.
                                running: false
                                status: Est at.
                                workflow_id: Odit ut reprehenderit molestiae.
        post:
            tags:
                - batch
            summary: submit batch
            description: Submit a new batch
            operationId: batch#submit
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SubmitRequestBody'
                        example:
                            completed_dir: In laudantium consequatur ducimus quis.
                            path: Nesciunt reiciendis tempore ut dignissimos.
                            retention_period: Minus praesentium.
            responses:
                "202":
                    description: Accepted response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BatchResult'
                            example:
                                run_id: Nihil voluptatem et numquam consequatur fuga nisi.
                                workflow_id: Necessitatibus accusantium doloribus corrupti enim.
                "400":
                    description: 'not_valid: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'not_available: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /batch/hints:
        get:
            tags:
                - batch
            summary: hints batch
            description: Retrieve form hints
            operationId: batch#hints
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BatchHintsResult'
                            example:
                                completed_dirs:
                                    - Assumenda in assumenda ea.
                                    - Totam repellat iure nostrum eaque.
    /package:
        get:
            tags:
                - package
            summary: list package
            description: List all stored packages
            operationId: package#list
            parameters:
                - name: name
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: Harum totam sit inventore impedit voluptates vel.
                  example: Id corrupti quia praesentium.
                - name: aip_id
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: B140526E-56D0-0183-0B79-28E8969E1B3C
                    format: uuid
                  example: 3B15D937-70A4-0C6D-371A-A0BDAF451237
                - name: earliest_created_time
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: "2014-07-09T07:11:51Z"
                    format: date-time
                  example: "1984-10-07T05:40:16Z"
                - name: latest_created_time
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: "1979-02-13T15:28:44Z"
                    format: date-time
                  example: "1998-06-12T19:24:20Z"
                - name: status
                  in: query
                  allowEmptyValue: true
                  schema:
                    type: string
                    example: done
                    enum:
                        - new
                        - in progress
                        - done
                        - error
                        - unknown
                        - queued
                        - pending
                        - abandoned
                  example: in progress
                - name: cursor
                  in: query
                  description: Pagination cursor
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Pagination cursor
                    example: Quam et aut quia est provident sequi.
                  example: At ex omnis quo dignissimos atque autem.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListResponseBody'
                            example:
                                items:
                                    - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                                      completed_at: "1981-07-18T09:32:04Z"
                                      created_at: "1983-12-07T23:41:35Z"
                                      id: 2608592925037585396
                                      name: Vitae illum magni placeat quo.
                                      run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                                      started_at: "1998-03-18T12:36:31Z"
                                      status: error
                                      workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                                    - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                                      completed_at: "1981-07-18T09:32:04Z"
                                      created_at: "1983-12-07T23:41:35Z"
                                      id: 2608592925037585396
                                      name: Vitae illum magni placeat quo.
                                      run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                                      started_at: "1998-03-18T12:36:31Z"
                                      status: error
                                      workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                                next_cursor: Et deleniti voluptatem beatae.
    /package/{id}:
        delete:
            tags:
                - package
            summary: delete package
            description: Delete package by ID
            operationId: package#delete
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to delete
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to delete
                    example: 2612763728360051995
                  example: 10656378748426724814
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageNotfound'
        get:
            tags:
                - package
            summary: show package
            description: Show package by ID
            operationId: package#show
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to show
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to show
                    example: 16309157576694495571
                  example: 16449755803814643389
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EnduroStoredPackage'
                            example:
                                aip_id: 2AE5027E-EF4C-E00D-314E-1CB4449A11C0
                                completed_at: "2000-02-19T03:42:45Z"
                                created_at: "1985-10-08T06:13:45Z"
                                id: 4074833407011102259
                                name: Vel maiores aliquam dolorum odio.
                                run_id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
                                started_at: "2006-12-16T00:49:52Z"
                                status: abandoned
                                workflow_id: 0E0CB887-B526-812D-F285-DE018C555BB8
                "404":
                    description: 'not_found: Package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageNotfound'
    /package/{id}/cancel:
        post:
            tags:
                - package
            summary: cancel package
            description: Cancel package processing by ID
            operationId: package#cancel
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to remove
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to remove
                    example: 16285322773772856172
                  example: 533707219424226902
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'not_running: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageNotfound'
    /package/{id}/confirm:
        post:
            tags:
                - package
            summary: confirm package
            description: Signal the package has been reviewed and accepted
            operationId: package#confirm
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to look up
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to look up
                    example: 14306869750223661883
                  example: 4867273123764600371
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ConfirmRequestBody'
                        example:
                            location: Et dignissimos explicabo soluta et autem id.
            responses:
                "202":
                    description: Accepted response.
                "400":
                    description: 'not_valid: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'not_available: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /package/{id}/preservation-actions:
        get:
            tags:
                - package
            summary: preservation-actions package
            description: List all preservation actions by ID
            operationId: package#preservation-actions
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to look up
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to look up
                    example: 12074649706106816166
                  example: 15764990649707877644
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EnduroPackagePreservationActions'
                            example:
                                actions:
                                    - action_id: Veritatis cumque.
                                      id: 17014779284437445999
                                      name: Quod impedit sapiente ea.
                                      started_at: "2015-08-09T01:52:06Z"
                                      status: processing
                                    - action_id: Veritatis cumque.
                                      id: 17014779284437445999
                                      name: Quod impedit sapiente ea.
                                      started_at: "2015-08-09T01:52:06Z"
                                      status: processing
                                    - action_id: Veritatis cumque.
                                      id: 17014779284437445999
                                      name: Quod impedit sapiente ea.
                                      started_at: "2015-08-09T01:52:06Z"
                                      status: processing
                                    - action_id: Veritatis cumque.
                                      id: 17014779284437445999
                                      name: Quod impedit sapiente ea.
                                      started_at: "2015-08-09T01:52:06Z"
                                      status: processing
                "404":
                    description: 'not_found: Package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageNotfound'
    /package/{id}/reject:
        post:
            tags:
                - package
            summary: reject package
            description: Signal the package has been reviewed and rejected
            operationId: package#reject
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to look up
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to look up
                    example: 13213208546802424006
                  example: 17369465478775088819
            responses:
                "202":
                    description: Accepted response.
                "400":
                    description: 'not_valid: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'not_available: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /package/{id}/retry:
        post:
            tags:
                - package
            summary: retry package
            description: Retry package processing by ID
            operationId: package#retry
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to retry
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to retry
                    example: 15376893229714102866
                  example: 17904440249896913616
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'not_running: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageNotfound'
    /package/{id}/workflow:
        get:
            tags:
                - package
            summary: workflow package
            description: Retrieve workflow status by ID
            operationId: package#workflow
            parameters:
                - name: id
                  in: path
                  description: Identifier of package to look up
                  required: true
                  schema:
                    type: integer
                    description: Identifier of package to look up
                    example: 590393454336128093
                  example: 12645354768276093995
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EnduroPackageWorkflowStatus'
                            example:
                                history:
                                    - details: Ut reprehenderit eos consequuntur iusto.
                                      id: 8869941666368485627
                                      type: Amet rerum quam sequi.
                                    - details: Ut reprehenderit eos consequuntur iusto.
                                      id: 8869941666368485627
                                      type: Amet rerum quam sequi.
                                status: Quia molestiae ut eaque vero.
                "404":
                    description: 'not_found: Package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PackageNotfound'
    /package/bulk:
        get:
            tags:
                - package
            summary: bulk_status package
            description: Retrieve status of current bulk operation.
            operationId: package#bulk_status
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BulkStatusResult'
                            example:
                                closed_at: "2012-10-15T09:29:37Z"
                                run_id: Neque eum voluptate architecto accusantium sapiente.
                                running: false
                                started_at: "1998-03-19T14:54:23Z"
                                status: Officiis sint.
                                workflow_id: Odit in quia tempora.
        post:
            tags:
                - package
            summary: bulk package
            description: Bulk operations (retry, cancel...).
            operationId: package#bulk
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BulkRequestBody'
                        example:
                            operation: retry
                            size: 13733910633092730650
                            status: done
            responses:
                "202":
                    description: Accepted response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BatchResult'
                            example:
                                run_id: Ea error earum.
                                workflow_id: Sapiente aliquid iure quia et.
                "400":
                    description: 'not_valid: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'not_available: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /package/monitor:
        get:
            tags:
                - package
            summary: monitor package
            operationId: package#monitor
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EnduroMonitorUpdate'
                            example:
                                id: 5760259863361402561
                                item:
                                    aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                                    completed_at: "1981-07-18T09:32:04Z"
                                    created_at: "1983-12-07T23:41:35Z"
                                    id: 2608592925037585396
                                    name: Vitae illum magni placeat quo.
                                    run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                                    started_at: "1998-03-18T12:36:31Z"
                                    status: error
                                    workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                                type: Facere autem doloribus sed tempore voluptatum.
    /storage/{aip_id}/download:
        get:
            tags:
                - storage
            summary: download storage
            description: Download package by AIPID
            operationId: storage#download
            parameters:
                - name: aip_id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Amet adipisci delectus impedit ea molestiae.
                  example: Sint aperiam suscipit nisi.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example:
                                    - 68
                                    - 105
                                    - 103
                                    - 110
                                    - 105
                                    - 115
                                    - 115
                                    - 105
                                    - 109
                                    - 111
                                    - 115
                                    - 32
                                    - 100
                                    - 101
                                    - 98
                                    - 105
                                    - 116
                                    - 105
                                    - 115
                                    - 46
                                format: binary
                            example:
                                - 82
                                - 101
                                - 114
                                - 117
                                - 109
                                - 32
                                - 101
                                - 120
                                - 112
                                - 108
                                - 105
                                - 99
                                - 97
                                - 98
                                - 111
                                - 32
                                - 101
                                - 115
                                - 116
                                - 32
                                - 97
                                - 108
                                - 105
                                - 113
                                - 117
                                - 105
                                - 100
                                - 46
                "404":
                    description: 'not_found: Storage package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoragePackageNotfound'
    /storage/{aip_id}/store:
        get:
            tags:
                - storage
            summary: move_status storage
            description: Retrieve the status of a permanent storage location move of the package
            operationId: storage#move_status
            parameters:
                - name: aip_id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Alias aut dolore.
                  example: Assumenda qui assumenda suscipit.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MoveStatusResult'
                            example:
                                done: false
                "404":
                    description: 'not_found: Storage package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoragePackageNotfound'
        post:
            tags:
                - storage
            summary: move storage
            description: Move a package to a permanent storage location
            operationId: storage#move
            parameters:
                - name: aip_id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Et autem adipisci et occaecati quaerat.
                  example: Nostrum ab pariatur non.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ConfirmRequestBody'
                        example:
                            location: Tempora voluptatem rerum.
            responses:
                "202":
                    description: Accepted response.
                "400":
                    description: 'not_valid: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Storage package not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoragePackageNotfound'
                "409":
                    description: 'not_available: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /storage/{aip_id}/submit:
        post:
            tags:
                - storage
            summary: submit storage
            description: Start the submission of a package
            operationId: storage#submit
            parameters:
                - name: aip_id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Quos fugit.
                  example: Mollitia ea aliquam.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SubmitRequestBody2'
                        example:
                            name: Nesciunt qui est provident fuga aut consequatur.
            responses:
                "202":
                    description: Accepted response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SubmitResult'
                            example:
                                url: Ea recusandae quasi voluptatem iusto consequatur qui.
                "400":
                    description: 'not_valid: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'not_available: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /storage/{aip_id}/update:
        post:
            tags:
                - storage
            summary: update storage
            description: Signal the storage service that an upload is complete
            operationId: storage#update
            parameters:
                - name: aip_id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Et et suscipit in omnis.
                  example: Nostrum quis delectus quod a.
            responses:
                "202":
                    description: Accepted response.
                "400":
                    description: 'not_valid: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "409":
                    description: 'not_available: Conflict response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /storage/location:
        get:
            tags:
                - storage
            summary: list storage
            description: List locations
            operationId: storage#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredLocationResponseCollection'
                            example:
                                - id: Neque natus quaerat dicta sit voluptatibus.
                                  name: Consequatur laudantium excepturi rem.
                                - id: Neque natus quaerat dicta sit voluptatibus.
                                  name: Consequatur laudantium excepturi rem.
                                - id: Neque natus quaerat dicta sit voluptatibus.
                                  name: Consequatur laudantium excepturi rem.
    /swagger/swagger.json:
        get:
            tags:
                - swagger
            summary: Download internal/api/gen/http/openapi.json
            description: JSON document containing the API swagger definition.
            operationId: swagger#/swagger/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        BatchHintsResult:
            type: object
            properties:
                completed_dirs:
                    type: array
                    items:
                        type: string
                        example: Perferendis veritatis numquam alias et dolor.
                    description: A list of known values of completedDir used by existing watchers.
                    example:
                        - Dolorem aliquid.
                        - Nobis tempore vero ad id.
                        - Eveniet corrupti.
                        - Quibusdam excepturi nemo odit sint provident ea.
            example:
                completed_dirs:
                    - Delectus culpa reiciendis et.
                    - Vel rem et ipsam adipisci voluptas.
        BatchResult:
            type: object
            properties:
                run_id:
                    type: string
                    example: Aut doloremque occaecati suscipit.
                workflow_id:
                    type: string
                    example: Dolor eligendi esse.
            example:
                run_id: Eligendi voluptatum pariatur.
                workflow_id: Eius accusantium molestiae consequatur id a quo.
            required:
                - workflow_id
                - run_id
        BatchStatusResult:
            type: object
            properties:
                run_id:
                    type: string
                    example: Maiores et harum quam voluptatibus repellendus.
                running:
                    type: boolean
                    example: false
                status:
                    type: string
                    example: Et tempora ut.
                workflow_id:
                    type: string
                    example: Error ut molestiae id.
            example:
                run_id: Incidunt est dolore voluptatem.
                running: false
                status: Nihil ipsum sunt dolor tempora molestiae.
                workflow_id: Ullam sit rerum est ipsa.
            required:
                - running
        BulkRequestBody:
            type: object
            properties:
                operation:
                    type: string
                    example: abandon
                    enum:
                        - retry
                        - cancel
                        - abandon
                size:
                    type: integer
                    default: 100
                    example: 3565756785982268301
                status:
                    type: string
                    example: done
                    enum:
                        - new
                        - in progress
                        - done
                        - error
                        - unknown
                        - queued
                        - pending
                        - abandoned
            example:
                operation: abandon
                size: 9187249701858471502
                status: in progress
            required:
                - operation
                - status
        BulkStatusResult:
            type: object
            properties:
                closed_at:
                    type: string
                    example: "1972-06-20T09:45:48Z"
                    format: date-time
                run_id:
                    type: string
                    example: Cumque est.
                running:
                    type: boolean
                    example: true
                started_at:
                    type: string
                    example: "1978-05-26T22:46:57Z"
                    format: date-time
                status:
                    type: string
                    example: Id qui.
                workflow_id:
                    type: string
                    example: Laborum consequatur reprehenderit sint sit.
            example:
                closed_at: "2002-09-09T12:52:05Z"
                run_id: Qui et id.
                running: false
                started_at: "1993-03-09T10:07:23Z"
                status: Quidem voluptatum aut quia recusandae architecto.
                workflow_id: Qui excepturi iste aperiam laborum suscipit aut.
            required:
                - running
        ConfirmRequestBody:
            type: object
            properties:
                location:
                    type: string
                    example: Tenetur quibusdam rerum sit labore.
            example:
                location: Quia id.
            required:
                - location
        EnduroMonitorUpdate:
            type: object
            properties:
                id:
                    type: integer
                    description: Identifier of package
                    example: 1609407489009853480
                item:
                    $ref: '#/components/schemas/EnduroStoredPackage'
                type:
                    type: string
                    description: Type of the event
                    example: Enim est in laudantium vero sit.
            example:
                id: 16617607184658261710
                item:
                    aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                    completed_at: "1981-07-18T09:32:04Z"
                    created_at: "1983-12-07T23:41:35Z"
                    id: 2608592925037585396
                    name: Vitae illum magni placeat quo.
                    run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                    started_at: "1998-03-18T12:36:31Z"
                    status: error
                    workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                type: Ut sunt consequatur ex eius qui soluta.
            required:
                - id
                - type
        EnduroPackagePreservationActions:
            type: object
            properties:
                actions:
                    $ref: '#/components/schemas/EnduroPackagePreservationActionsActionCollection'
            example:
                actions:
                    - action_id: Veritatis cumque.
                      id: 17014779284437445999
                      name: Quod impedit sapiente ea.
                      started_at: "2015-08-09T01:52:06Z"
                      status: processing
                    - action_id: Veritatis cumque.
                      id: 17014779284437445999
                      name: Quod impedit sapiente ea.
                      started_at: "2015-08-09T01:52:06Z"
                      status: processing
                    - action_id: Veritatis cumque.
                      id: 17014779284437445999
                      name: Quod impedit sapiente ea.
                      started_at: "2015-08-09T01:52:06Z"
                      status: processing
                    - action_id: Veritatis cumque.
                      id: 17014779284437445999
                      name: Quod impedit sapiente ea.
                      started_at: "2015-08-09T01:52:06Z"
                      status: processing
        EnduroPackagePreservationActionsAction:
            type: object
            properties:
                action_id:
                    type: string
                    example: Possimus vero.
                id:
                    type: integer
                    example: 16743050768905223400
                name:
                    type: string
                    example: Omnis praesentium modi cum illum id.
                started_at:
                    type: string
                    example: "1993-04-23T01:44:43Z"
                    format: date-time
                status:
                    type: string
                    example: failed
                    enum:
                        - unspecified
                        - complete
                        - processing
                        - failed
            description: PreservationAction describes a preservation action.
            example:
                action_id: Eius fugiat laborum totam.
                id: 6734567845885491806
                name: Et magni consequuntur.
                started_at: "1997-06-26T03:40:29Z"
                status: complete
            required:
                - id
                - action_id
                - name
                - status
                - started_at
        EnduroPackagePreservationActionsActionCollection:
            type: array
            items:
                $ref: '#/components/schemas/EnduroPackagePreservationActionsAction'
            example:
                - action_id: Veritatis cumque.
                  id: 17014779284437445999
                  name: Quod impedit sapiente ea.
                  started_at: "2015-08-09T01:52:06Z"
                  status: processing
                - action_id: Veritatis cumque.
                  id: 17014779284437445999
                  name: Quod impedit sapiente ea.
                  started_at: "2015-08-09T01:52:06Z"
                  status: processing
                - action_id: Veritatis cumque.
                  id: 17014779284437445999
                  name: Quod impedit sapiente ea.
                  started_at: "2015-08-09T01:52:06Z"
                  status: processing
        EnduroPackageWorkflowHistory:
            type: object
            properties:
                details:
                    type: string
                    description: Contents of the event
                    example: Voluptates numquam dolorem.
                    format: binary
                id:
                    type: integer
                    description: Identifier of package
                    example: 7435248039005621700
                type:
                    type: string
                    description: Type of the event
                    example: Autem dolor architecto facere.
            description: WorkflowHistoryEvent describes a history event in Temporal.
            example:
                details: Fugiat et porro eum ut quod.
                id: 14699676190580707333
                type: Eaque vel deleniti.
        EnduroPackageWorkflowHistoryCollection:
            type: array
            items:
                $ref: '#/components/schemas/EnduroPackageWorkflowHistory'
            example:
                - details: Ut reprehenderit eos consequuntur iusto.
                  id: 8869941666368485627
                  type: Amet rerum quam sequi.
                - details: Ut reprehenderit eos consequuntur iusto.
                  id: 8869941666368485627
                  type: Amet rerum quam sequi.
                - details: Ut reprehenderit eos consequuntur iusto.
                  id: 8869941666368485627
                  type: Amet rerum quam sequi.
                - details: Ut reprehenderit eos consequuntur iusto.
                  id: 8869941666368485627
                  type: Amet rerum quam sequi.
        EnduroPackageWorkflowStatus:
            type: object
            properties:
                history:
                    $ref: '#/components/schemas/EnduroPackageWorkflowHistoryCollection'
                status:
                    type: string
                    example: Officia quae non commodi et repellat consectetur.
            example:
                history:
                    - details: Ut reprehenderit eos consequuntur iusto.
                      id: 8869941666368485627
                      type: Amet rerum quam sequi.
                    - details: Ut reprehenderit eos consequuntur iusto.
                      id: 8869941666368485627
                      type: Amet rerum quam sequi.
                status: Est quo adipisci provident provident enim.
        EnduroStoredPackage:
            type: object
            properties:
                aip_id:
                    type: string
                    description: Identifier of Archivematica AIP
                    example: AF3C2FF8-1A90-BD97-39C4-B4426C5778CC
                    format: uuid
                completed_at:
                    type: string
                    description: Completion datetime
                    example: "1978-04-22T21:56:07Z"
                    format: date-time
                created_at:
                    type: string
                    description: Creation datetime
                    example: "2008-05-23T22:46:50Z"
                    format: date-time
                id:
                    type: integer
                    description: Identifier of package
                    example: 1313912653544545828
                name:
                    type: string
                    description: Name of the package
                    example: Ex assumenda.
                run_id:
                    type: string
                    description: Identifier of latest processing workflow run
                    example: 38F93803-BFA0-82D1-0649-B0769F6F7519
                    format: uuid
                started_at:
                    type: string
                    description: Start datetime
                    example: "2012-02-28T22:29:35Z"
                    format: date-time
                status:
                    type: string
                    description: Status of the package
                    default: new
                    example: error
                    enum:
                        - new
                        - in progress
                        - done
                        - error
                        - unknown
                        - queued
                        - pending
                        - abandoned
                workflow_id:
                    type: string
                    description: Identifier of processing workflow
                    example: 86EDFB6E-94F4-2B51-2B7E-E4683F848FD6
                    format: uuid
            description: StoredPackage describes a package retrieved by the service.
            example:
                aip_id: 34287C80-E47A-5C59-54F8-1AC4DAC80AFD
                completed_at: "1996-04-28T18:22:06Z"
                created_at: "1979-05-07T02:18:48Z"
                id: 10842074028899481040
                name: Eum nisi.
                run_id: EF5D214E-555E-4D58-0EF2-F45C1076AF15
                started_at: "1999-10-10T05:42:34Z"
                status: error
                workflow_id: 1883B2DF-F70A-5DB7-7F4C-C27752CD3BFF
            required:
                - id
                - status
                - created_at
        EnduroStoredPackageCollection:
            type: array
            items:
                $ref: '#/components/schemas/EnduroStoredPackage'
            example:
                - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  completed_at: "1981-07-18T09:32:04Z"
                  created_at: "1983-12-07T23:41:35Z"
                  id: 2608592925037585396
                  name: Vitae illum magni placeat quo.
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1998-03-18T12:36:31Z"
                  status: error
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                  completed_at: "1981-07-18T09:32:04Z"
                  created_at: "1983-12-07T23:41:35Z"
                  id: 2608592925037585396
                  name: Vitae illum magni placeat quo.
                  run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  started_at: "1998-03-18T12:36:31Z"
                  status: error
                  workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        ListResponseBody:
            type: object
            properties:
                items:
                    $ref: '#/components/schemas/EnduroStoredPackageCollection'
                next_cursor:
                    type: string
                    example: Similique quisquam voluptas libero.
            example:
                items:
                    - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                      completed_at: "1981-07-18T09:32:04Z"
                      created_at: "1983-12-07T23:41:35Z"
                      id: 2608592925037585396
                      name: Vitae illum magni placeat quo.
                      run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                      started_at: "1998-03-18T12:36:31Z"
                      status: error
                      workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                    - aip_id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
                      completed_at: "1981-07-18T09:32:04Z"
                      created_at: "1983-12-07T23:41:35Z"
                      id: 2608592925037585396
                      name: Vitae illum magni placeat quo.
                      run_id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                      started_at: "1998-03-18T12:36:31Z"
                      status: error
                      workflow_id: A464FD15-9F47-E3CC-BD80-3B5C5830C503
                next_cursor: Libero neque quam repudiandae adipisci quis dolores.
            required:
                - items
        MoveStatusResult:
            type: object
            properties:
                done:
                    type: boolean
                    example: true
            example:
                done: false
            required:
                - done
        PackageNotfound:
            type: object
            properties:
                id:
                    type: integer
                    description: Identifier of missing package
                    example: 9360361600696854982
                message:
                    type: string
                    description: Message of error
                    example: Voluptas sed rerum ipsam dicta.
            description: Package not found
            example:
                id: 2438492422200040730
                message: Doloremque aut.
            required:
                - message
                - id
        StoragePackageNotfound:
            type: object
            properties:
                aip_id:
                    type: string
                    description: Identifier of missing package
                    example: Nihil similique unde molestiae esse consequatur.
                message:
                    type: string
                    description: Message of error
                    example: Hic eveniet quam consequatur eveniet repellat.
            description: Storage package not found
            example:
                aip_id: Tenetur dolorum error aut.
                message: Animi veniam omnis dolores sed omnis.
            required:
                - message
                - aip_id
        StoredLocationResponse:
            type: object
            properties:
                id:
                    type: string
                    description: ID is the unique id of the location.
                    example: Et ut.
                name:
                    type: string
                    description: Name of location
                    example: Fuga sed sunt molestiae.
            description: A StoredLocation describes a location retrieved by the storage service. (default view)
            example:
                id: Et aliquid voluptatem animi est praesentium officiis.
                name: Magnam est veritatis ut autem.
            required:
                - id
                - name
        StoredLocationResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredLocationResponse'
            description: ListResponseBody is the result type for an array of StoredLocationResponse (default view)
            example:
                - id: Neque natus quaerat dicta sit voluptatibus.
                  name: Consequatur laudantium excepturi rem.
                - id: Neque natus quaerat dicta sit voluptatibus.
                  name: Consequatur laudantium excepturi rem.
                - id: Neque natus quaerat dicta sit voluptatibus.
                  name: Consequatur laudantium excepturi rem.
                - id: Neque natus quaerat dicta sit voluptatibus.
                  name: Consequatur laudantium excepturi rem.
        SubmitRequestBody:
            type: object
            properties:
                completed_dir:
                    type: string
                    example: Dolor et repudiandae.
                path:
                    type: string
                    example: Ut ut repudiandae modi adipisci.
                retention_period:
                    type: string
                    example: Tempore sunt maxime nulla quia.
            example:
                completed_dir: Cum consequatur non eos consequuntur aspernatur.
                path: Voluptatem ut.
                retention_period: Vero molestiae modi similique dolore.
            required:
                - path
        SubmitRequestBody2:
            type: object
            properties:
                name:
                    type: string
                    example: Deleniti sapiente dignissimos.
            example:
                name: Quo repellendus voluptas.
            required:
                - name
        SubmitResult:
            type: object
            properties:
                url:
                    type: string
                    example: Ut consequatur facilis vel quisquam maxime.
            example:
                url: Enim non ut hic.
            required:
                - url
tags:
    - name: batch
      description: The batch service manages batches of packages.
    - name: package
      description: The package service manages packages being transferred to a3m.
    - name: storage
      description: The storage service manages the storage of packages.
    - name: swagger
      description: The swagger service serves the API swagger definition.
